version: "3.3"

services:

  greenely:
    build: ./greenely
    container_name: greenely
    restart: always
    environment:
      - APP_NAME=greenely
    expose:
      - 8181

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"