version: "3.3"

services:

  greenely:
    build: ./greenely
    container_name: greenely
    restart: always
    volumes:
      - static_volume:/home/app/greenely/static
    environment:
      - APP_NAME=greenely
    expose:
      - 8181

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    volumes:
      - static_volume:/home/app/greenely/static
    ports:
      - "80:80"
volumes:
   static_volume:
