DEVELOPMENT_ENVIRONMENT = 'development'
PRODUCTION_ENVIRONMENT = 'production'
LOCAL_ENVIRONMENT = 'local'
BASE_API_VERSION_URL = r'^api/v1'
CONSUMPTION_API_PATH = '/consumption/'
AUTH_API_PATH = '/auth/'
SWAGGER_API_PATH = '/swagger/'
CONSUMPTION_API_URL = '{0}{1}'.format(BASE_API_VERSION_URL,
                                      CONSUMPTION_API_PATH)
AUTH_API_URL = '{0}{1}'.format(BASE_API_VERSION_URL, AUTH_API_PATH)
SWAGGER_API_URL = '{0}{1}'.format(BASE_API_VERSION_URL, SWAGGER_API_PATH)
